version: 0.2

phases:

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
#      - mvn package
#      - mv target/menu-service.jar menu-service.jar
   
artifacts:
  files:
   - target/imagedefinitions.json
   - target/menu-service.jar
discard-paths: yes