version: 0.2

phases:

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
   
artifacts:
  files:
   - imagedefinitions.json
   - target/menu-service.jar
discard-paths: yes